### ISSUE TITLE
Unrar logic will result in partial or corrupt imports

### ISSUE THREAD

**Issue by bakerboy448** [fe80Grau/Rectificarr#1]
https://github.com/fe80Grau/Rectificarr/blob/295ab06bffefeb5e12e82e96ab00c572e4e78da8/posttorent.sh#L51

the script fails to unpack the files in a temporary folder or extension; this - like every other common attempts at unrar scripts - will result in sonarr/radarr importing partially unpacked files resulting in corrupt video files being imported

**Comment by fe80Grau** [comment]
I'm trying now with a little custom code in posttorrent.sh.
Before all, the script rename temporaly the current folder (i used base64 because was very fast implement it) . After all, the script rename again to original name.
