### ISSUE TITLE
NotADirectoryError: [Errno20]

### ISSUE THREAD

**Issue by simian91** [fe80Grau/Rectificarr#2]
First of all many thanks for this awesome script! I'm running both radarr and qbittorrent (latest versions) via docker containers on debian.

I'm getting the following error:

`NotADirectoryError: [Errno 20] Not a directory: 'directories/media/downloads/movies/MOVIENAME [BluRay 1080p][AC3 5.1 Castellano AC3 5.1-Ingles+Subs][ES-EN]/MOVIENAME BD1080.www.atomohd.lol.mkv/MOVIENAME BD1080.www.atomohd.lol.mkv' -> 'directories/media/downloads/movies/MOVIENAME [BluRay 1080p][AC3 5.1 Castellano AC3 5.1-Ingles+Subs][ES-EN]/MOVIENAME BD1080.www.atomohd.lol.mkv/MOVIENAME (2022) Bluray-1080p.mkv'`

It seems the 'source' reference in the script produces the full path including .mkv file. So we're get these double directories when we add the .mkv file:

`shutil.move(source + "/" + file, source + "/" + new_name)`

resulting in the directory error. Is that something easily addressed?

**Comment by fe80Grau** [comment]
Check if this works for you. https://github.com/fe80Grau/Rectificarr/commit/939c7ed9883b8de0407e7e21a3580522dd334c9f

**Comment by simian91** [comment]
Thanks for the update! When I run it, it gives me the following error:

`Trying to rename and move to correct folder
Old name: ElHobbitLaDesolaciónDeSmaugM1080.www.newpct.com.mkv
New name: The Hobbit: The Desolation of Smaug (2013) HDTV-1080p.mkv
Traceback (most recent call last):
  File "/opt/Rectificarr/main2.py", line 97, in <module>
    if(os.path.isfile(source)):
NameError: name 'os' is not defined`

**Comment by fe80Grau** [comment]
TY for reply, i fixed this in main branch
