### ISSUE TITLE
Successful rename but failed import

### ISSUE THREAD

**Issue by simian91** [fe80Grau/Rectificarr#4]
hi again fe80Grau,

Ran into an issue that is seemingly random and only occurs for some downloads: they show up with a parsing error and get successfully renamed, yet afterwards (instead of importing), radarr changes the error to something like the following:

`No files found are eligible for import in /srv/xxx/es/torrents/movies/El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com]/El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com].avi`

Note, that the file was succesfully renamed from `El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com].avi` to `The Lord of the Rings/ The Two Towers (2002) Bluray-480p.avi`

It seems like radarr is looking in the wrong folder (should be looking in `/srv/xxx/es/torrents/movies/El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com]/` without the filename. 

Seems like a radarr or qbittorrent issue - but perhaps you have thoughts on this. Thanks!

**Comment by eduardoruizgr** [comment]
Hi!

I am also having the exactly same issue as simian91. So I once I have the movie downloaded I get the parsing error and then after the script comes in (very nicely) and renames them radarr kinda forgets about them and I end up without the movie. 

Not sure what to do at the moment since I am quite lost

**Comment by fe80Grau** [comment]
Hi!
I rewritted a little bit this script. Try again pulling the latest main, i think that this code can solve this question. 
Now is not rennaming the file in torrent folder, instead of this the file is copied to final movie path   (like "natural" import process), after that 2 request is needed.  /manualimport and /command with RescanMovie param.

Please check it and tell me.

*If yout want to delete movie from queue uncomment lines 208 to 218. Be carefoul this lines will delete the torrent file.

**Comment by simian91** [comment]
That sounds like it should do the trick indeed. For now though I'm presented with the following when I run the latest main:

`Rectificarr is running...
Processing data from Radarr
Traceback (most recent call last):
  File "/opt/Rectificarr/main.py", line 146, in <module>
    for f in os.listdir(source):
NotADirectoryError: [Errno 20] Not a directory: '/srv/dev-disk-by-uuid-e548a312-418d-4b92-8cc4-911009fce9df/data/es/torrents/movies/El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com]/El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com].avi'`

Any thoughts? Thanks again.

**Comment by simian91** [comment]
That sounds like it should do the trick indeed. For now though I'm presented with the following when I run the latest main:

`Rectificarr is running... Processing data from Radarr Traceback (most recent call last): File "/opt/Rectificarr/main.py", line 146, in <module> for f in os.listdir(source): NotADirectoryError: [Errno 20] Not a directory: '/data/es/torrents/movies/El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com]/El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com].avi`

Any thoughts? Thanks again.

**Comment by fe80Grau** [comment]
Very sorry, i mistaked in source and file_source condtion to determine if a movie is in folder. Check las commit in main. I hope that will works.
https://github.com/fe80Grau/Rectificarr/commit/6391271072242e21a969a45398871dc357020067

**Comment by simian91** [comment]
Many thanks for the quick iterations! Right now, it's a different error I'm presented with: 

```
Rectificarr is running...
Processing data from Radarr
||||| The Lord of the Rings: The Two Towers
|||||||||| Movie warning detectect: 55 - The Lord of the Rings: The Two Towers/El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com].avi
- Trying to rename and move to correct folder
- Old name: El Senor de los Anillos-Las dos torres.[HDrip][Spanish][ToDoTorrente.com].avi
- New name: The Lord of the Rings: The Two Towers (2002) Bluray-480p.avi
|||||Importing movie... 
Traceback (most recent call last):
  File "/opt/Rectificarr/main.py", line 179, in <module>
    shutil.copy(mv_source, "{}/{}".format(path, new_name))
  File "/usr/lib/python3.9/shutil.py", line 418, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/data/es/media/movies/The Lord of the Rings The Two Towers (2002) [imdbid-tt0167261]/The Lord of the Rings: The Two Towers (2002) Bluray-480p.avi'

**Comment by fe80Grau** [comment]
I think that your error now is because the destination of movie folder setted by Radarr is missing. Check in your Raddar: Settings -> Media Management -> Show Advanced -> Create empty movie folders. If is checked the empty  folder of monitored movies will be created.  Please test it (or make an the movie folder manually)  while i fix the code to make folder when is missing.

**Comment by simian91** [comment]
Excellent this is what did the trick!! Superb work, thanks for all your efforts.

There is evidently one more edge case: there are torrents where the .mkv (or whatever movie file) is packed in several .rar files, which are automatically unpacked with unpackerr. When running the script after unpacking, it picks a .rar file to rename and import instead of the unpacked .mkv file:

```
Rectificarr is running...
Processing data from Radarr
||||| El señor de los anillos: Las dos torres
|||||||||| Movie warning detectect: 55 - El señor de los anillos: Las dos torres/ESDLA Las dos torres V.E.part03.rar
- Trying to rename and move to correct folder
- Old name: ESDLA Las dos torres V.E.part03.rar
- New name: El señor de los anillos: Las dos torres (2002) HDTV-1080p.rar
|||||Importing movie... 
import done
|||||Rescanning movie... 
Rescan done
```
Would there be an easy fix for such cases?

**Comment by fe80Grau** [comment]
I understand it, this code assumes file_source as an only movie file. mimetypes library probably can help us, with this library i think that I can check the file's mimetype and only get it if is a video.  I will work about this. *A fast solution: Delete the rar parts and keep only the movie file in folder

**Comment by simian91** [comment]
Indeed, trying to get unpackerr to remove the .rars after unpacking but somehow it's not doing that for the moment. 

On another note, I tried uncommenting the lines 208-218 (because even after successful rename & import, the no-parse error remains in radarr), but I'm presented with the following error:

```
|||||Deleting in queue...
Traceback (most recent call last):
  File "/opt/Rectificarr/main5.py", line 216, in <module>
    delete_result = requests.delete(delete_url_radarr, data=json.dumps(params_radarr)).json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Thanks again!

**Comment by fe80Grau** [comment]
> Indeed, trying to get unpackerr to remove the .rars after unpacking but somehow it's not doing that for the moment.
> 
> On another note, I tried uncommenting the lines 208-218 (because even after successful rename & import, the no-parse error remains in radarr), but I'm presented with the following error:
> 
> ```
> |||||Deleting in queue...
> Traceback (most recent call last):
>   File "/opt/Rectificarr/main5.py", line 216, in <module>
>     delete_result = requests.delete(delete_url_radarr, data=json.dumps(params_radarr)).json()
>   File "/usr/lib/python3/dist-packages/requests/models.py", line 900, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```
> 
> Thanks again!

Hi dude! try again with last commit in main. 
Changes:

* The folder setted by Radarr will be created if not exist
* Delete request now is working and won't remove the torrent file only removes movie from Radarr queue
* The order is changed, first the movie is removed from queue and then it is rescaned.

**Comment by simian91** [comment]
Amazing work man, it seems to be running super smooth now. Really great job, and a big thanks from me!

**Comment by eduardoruizgr** [comment]
Fernando! Excelente trabajo, al igual que simian91 has conseguido que funcione sin problema. Lo estoy utilizando y de momento todo va perfecto. Un places y enhorabuena!
