### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by eduardoruizgr** [fe80Grau/Rectificarr#5]
Hi Fernando,

I've been using your script for almost 3 months already and I can't say enough how good it is. However, in the past week I've been having one issue that has led to the script not working as before. So I have the script running every 5 minutes and I have recently encounter an error that spits "List index out of range" (see the image attached). Would you be able to help me out?

Thank you so much!

![Rectificarr error](https://github.com/fe80Grau/Rectificarr/assets/63683133/85f306e3-1732-403e-8518-a69f4c637808)

**Comment by fe80Grau** [comment]
Hi @eduardoruizgr , i added two lines to debug your error, please pull last commit and paste here  full output. If you can tell me more about torrent (tracker and item)?

**Comment by eduardoruizgr** [comment]
Hola fer! Lo he probado y parece que funciona muchisimas gracias. Si sale algun error mas te voy comentando pero de momento todo perfecto. Muchisimas gracias
