### ISSUE TITLE
outputpath error

### ISSUE THREAD

**Issue by alejandrodt** [fe80Grau/Rectificarr#6]
hi!

i am trying to use Rectificarr but i am facing problems.
My Radarr is in version 5.11.0.9244, and working in docker compose. Everything is fine except the name of spanish tracker films :) 

I want to use rectificarr for helping radarr to parse names.

Once i clone the repository, i have an error: FileNotFoundError: [Errno 2] No such file or directory: 'config.json'
I solved it by modifying the code "open('config.json', 'r')" to "open('/opt/rectificarr/config.json', 'r')". But i am facing other problem.

When i try to run: /usr/bin/python3 /opt/Rectificarr/main.py
I receive the following error:

Traceback (most recent call last):
  File "/opt/Rectificarr/main.py", line 159, in <module>
    source = item['OutputPath']
             ~~~~^^^^^^^^^^^^^^
KeyError: 'OutputPath'

I couldn't find a solution. could you please help me? thnks!

**Comment by fe80Grau** [comment]
Hi, it's weird that you have the first "o" in uppercase OutputPath , in the original code it is in lowercase outputPath, which is how it is declared in the official answer from radarr for the enpoint https://radarr.video/docs/api/#/Queue/get_api_v3_queue .

Please try changing item['OutputPath'] to item['outputPath'] on line 158 of main.py

**Comment by alejandrodt** [comment]
hi!
Thanks for your help. It was me changing the coding and i wrote it in a bad way. I did it because it was not working.
Finally, to solve the problem, i decided to eliminate rectificarr and install it directly in linux instead of using docker compose, and now looks well!
